name: Python matrix CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: aquasecurity/vuln-list
        path: vuln-list
        fetch-depth: '1'
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --statistics
    - name: Test with pytest
      run: |
        pytest --cov=vdb test
      env:
        PYTHONPATH: .
    - name: Cache data
      run: |
        mkdir vdb_data vdb_cache
        rm -rf ./vuln-list/cwe ./vuln-list/alpine* ./vuln-list/debian ./vuln-list/ghsa ./vuln-list/.git ./vuln-list/glad ./vuln-list/go ./vuln-list/kevc ./vuln-list/mariner ./vuln-list/nvd ./vuln-list/osv ./vuln-list/oval
        zip -q -r vuln-list.zip ./vuln-list/
        mv vuln-list.zip vdb_cache/
        rm -rf ./vuln-list/
        python vdb/cli.py --cache-os
        ls -lh vdb_data
        ls -lh vdb_cache
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYTHONPATH: .
        VDB_HOME: vdb_data
        VDB_CACHE: vdb_cache
    - name: Test without orjson
      run: |
        pip uninstall -y orjson
        pytest --cov=vdb test
    - name: Self sast-scan
      uses: AppThreat/sast-scan-action@master
      with:
        output: reports
        type: python,credscan
      env:
        SCAN_ID: ${{ github.sha }}
        WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
    - name: Upload scan reports
      uses: actions/upload-artifact@v1.0.0
      with:
        name: sast-scan-reports
        path: reports
